# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 179dc145be15b79b4950bcda4045b786584e497d9211e195e509e50121a79a8ea5a369f8c7dba73138176bfbb3d8f6ff49cc722567da625fc7d655463424370d

test:
  secret_key_base: 1fcc3f2ea35190756898a6b7dd986660f3628f4a0314a4d5a625ae3929e803920447fd4d9f908243c47e349dd17e1ffa0a381a11f0d34bc5fd488e1db950211a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
